name: CI/CD for Astro

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # fetch the entire history

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Install dependencies
      run: npm ci

    - name: Build and Deploy
      env:
        REPO_NAME: astro-template
        REPO_OWNER: joni0108
        ASTRO_API_KEY: ${{ secrets.ASTRO_API_KEY }}  # Set this as a GitHub secret
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}  # Set this as a GitHub secret
      run: |
        npm run build
        # Deploy the built site to Vercel
        npx vercel --prod --token $VERCEL_TOKEN
